baseurl      = "https://cyber-raskolnikov.github.io"
title        = "cyber caveman's blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
themesDir    = "themes"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006"

  # Subtitle for home
  homeSubtitle = "thoughts of a computer scientist"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "cyber caveman's blog"
    subtitle = "reflections of a computer scientist"
    keywords = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about_me"
    name       = "about"
    url        = "/about"
